#!/usr/bin/env bash

# COLORS
BLUE='\033[0;34m'
BBLUE='\033[1;34m'
BYELLOW='\033[1;33m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'
VERSION="SubDog v1.0"

banner(){
    echo -e "${GREEN}
\t\t ___  __  __  ____  ____  _____  ___ 
\t\t/ __)(  )(  )(  _ \(  _ \(  _  )/ __)
\t\t\__ \ )(__)(  ) _ < )(_) ))(_)(( (_-.
\t\t(___/(______)(____/(____/(_____)\___/
\t\t${VERSION}                    coded by ${YELLOW}@rix4uni${RED} in INDIA${RESET}"
}

showhelp(){
    banner
    echo -e "${GREEN}TARGET OPTIONS${RESET}"
    echo -e "   -d, --domain			Single Target domain (domain.com)"
    echo -e ""
    echo -e "${GREEN}USAGE EXAMPLES${RESET}"
    echo -e "   ${BYELLOW}subdog -d example.com${RESET}"
    echo -e ""
}

if [[ ! -x "$(command -v jq)" ]]; then
	printf "${BBLUE}Installing jq\n\n"
	if [ -f /etc/os-release ]; then apt install jq -y &>/dev/null;
	elif [ -f /etc/redhat-release ]; then yum install jq -y &>/dev/null;
	elif [ -f /etc/arch-release ]; then sudo pacman -S jq -y &>/dev/null;
	fi
fi

passive_scan(){
	company_name=${domain%%.*}
	copyright=$3
	curl -s "https://rapiddns.io/subdomain/$domain?full=1#result" | grep "$company_name" | sed 's/<\/\?[^>]\+>//g' | sed '/<a$/d' | sed '1,3d' | sed '/\.$/d' | anew
	curl -s "https://api.threatminer.org/v2/domain.php?q=$domain&rt=5" | jq -r '.results[]' | anew
	curl -s "https://riddler.io/search/exportcsv?q=pld:$domain" | cut -d "," -f6 | sed '1,2d' | anew
	curl -s "https://otx.alienvault.com/api/v1/indicators/domain/$domain/passive_dns" | jq -r '.passive_dns[].hostname' | grep -i "$company_name" | anew
	curl --insecure --silent "http://web.archive.org/cdx/search/cdx?url=*.$domain/*&output=text&fl=original&collapse=urlkey" | unfurl -u domains | anew
	curl -s "https://api.hackertarget.com/hostsearch/?q=$domain" | cut -f1 -d"," | anew
	curl -s "https://crt.sh/?q=%25.$domain&output=json" | jq -r '.[] | {name_value:.name_value, common_name:.common_name}[]' | grep -i "$company_name" | anew
	# curl -s "https://crt.sh/?q=%25.$copyright&output=json" | jq -r '.[].common_name' | anew
	curl -s "https://jldc.me/anubis/subdomains/$domain" | jq -r '.[]' | anew
	curl -s "https://urlscan.io/api/v1/search/?q=domain:$domain" | jq -r '.results[] | {page:.page.domain, task:.task.domain}[]' | grep "$company_name" | anew
	python3 ~/tool/SubDog/c99.py -d $domain -t 100 | anew
}

while [ -n "$1" ]; do
    case $1 in
        -d|--domain)
            domain=$2
            passive_scan
            exit 0 ;;

        -v|--version)
            echo "$VERSION"
            exit 0 ;;

        -h|--help)
            showhelp
            exit 1 ;;

    esac
done
